### ISSUE TITLE
Infinite loading for translation

### ISSUE THREAD

**Issue by baeharam** [outsideris/issue-translator-extention#17]
요즘 깃헙에서 보는 프로젝트가 있어서 이슈를 쉽게 읽기 위해 이용해보려고 확장프로그램을 깔았습니다.
근데 로딩화면만 뜨고 번역은 안되는 무한로딩 상태에 걸리는데 어떻게 해결하죠? 구글 클라우드에서 API 키를 받아 확장 프로그램에 등록까지 했습니다.

**Comment by baeharam** [comment]
보니까 이런 에러가 있네요
![default](https://user-images.githubusercontent.com/35518072/40767451-884fb2de-64ed-11e8-9b5a-dd190aff8c74.JPG)

**Comment by outsideris** [comment]
403이 발생하는군요. 이건 구글쪽에서 응답을 저렇게 준건데 
혹시 API키를 만드신 다음에 Translation API 를 사용설정 하셨나요?

**Comment by baeharam** [comment]
넵 구글 클라우드에서 API 키를 받은 다음 설정했습니다.

**Comment by outsideris** [comment]
@baeharam 0.5.2를 배포했습니다. 주신 스크린샷처럼 오류메시지가 정확히 나오지 않아서 구글에서 받은 오류메시지가 console에 출력되도록 수정했습니다. 한번 확인해 보시겠어요?
